version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build

hooks:
  ApplicationStart:
    - location: script/code-deploy/application_start.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: script/code-deploy/application_stop.sh
      timeout: 120
      runas: root